# Build development environments (manylinux x86 or aarch, 64-bit)
# to locally build and publish solarwinds_apm Python APM library
version: '2.4'

services:
  x86:
    image: quay.io/pypa/manylinux2014_x86_64
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./:/code/solarwinds_apm
      - ../solarwinds-apm-liboboe/:/code/solarwinds-apm-liboboe
    working_dir: /code/solarwinds_apm
    entrypoint: ["/bin/bash", "-c"]
    command: 
    - |
       # boto3 for interaction with AWS
       # twine to upload to TestPyPi
       # tox for automated tests
       python3.8 -m pip install boto3 twine tox
       /bin/bash
    environment:
      - PLATFORM=x86_64
      - WHEEL_TAG=manylinux2014_x86_64
      - CP38_WHEEL=cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

  aarch:
    image: quay.io/pypa/manylinux2014_aarch64
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./:/code/solarwinds_apm
      - ../solarwinds-apm-liboboe/:/code/solarwinds-apm-liboboe
    working_dir: /code/solarwinds_apm
    entrypoint: ["/bin/bash", "-c"]
    command: 
    - |
       # boto3 for interaction with AWS
       # twine to upload to TestPyPi
       # tox for automated tests
       python3.8 -m pip install boto3 twine tox
       /bin/bash
    environment:
      - PLATFORM=aarch64
      - WHEEL_TAG=linux_aarch64
      - CP38_WHEEL=cp38-cp38-manylinux_2_24_aarch64.linux_aarch64.whl
