[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "solarwinds_apm"
description = "Custom distro for OpenTelemetry to connect to SolarWinds"
authors = [
    "SolarWinds, LLC <support@appoptics.com>"
]
license = {file = "LICENSE"}
readme = "README.md"
repository = "https://pypi.python.org/pypi/solarwinds_apm"
homepage = "https://www.appoptics.com/monitor/python-performance"
keywords = ["solarwinds_apm", "appoptics_apm", "traceview", "tracelytics", "oboe", "liboboe", "instrumentation", "performance"]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
]
dependencies = [
    "opentelemetry-api==1.12.0rc1",
    "opentelemetry-sdk==1.12.0rc1",
    "opentelemetry-instrumentation==0.31b0",
]
packages = [
    "solarwinds_apm",
    "solarwinds_apm.extension"
]
dynamic = ["version"]

[tool.setuptools.entry-points]
opentelemetry_distro =
    solarwinds_distro = "solarwinds_apm.distro:SolarWindsDistro"
opentelemetry_configurator =
    solarwinds_configurator = "solarwinds_apm.configurator:SolarWindsConfigurator"
opentelemetry_propagator =
    solarwinds_propagator = "solarwinds_apm.propagator:SolarWindsPropagator"
opentelemetry_traces_exporter =
    solarwinds_exporter = "solarwinds_apm.exporter:SolarWindsSpanExporter"
opentelemetry_traces_sampler =
    solarwinds_sampler = "solarwinds_apm.sampler:ParentBasedSwSampler"

[tool.setuptools.packages.find]
where = ["solarwinds_apm"]

[tool.setuptools.package-data]
solarwinds_apm = [
    "extension/liboboe-1.0.so.0",
    "extension/VERSION",
    "extension/bson/bson.h",
    "extension/bson/platform_hacks.h"
]

[tool.setuptools.dynamic]
version = {attr = "solarwinds_apm.version.__version__"}
