# © 2023 SolarWinds Worldwide, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at:http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

name: Publish to PackageCloud

on:
  workflow_dispatch:

jobs:
  build_publish_sdist_and_x86_64:
    name: Build and publish sdist and x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Ruby 3.1.1
      run: |
        sudo apt-get update -y
        sudo apt-get install libssl-dev libreadline-dev libgdbm-dev openssl
        gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && \
        curl -sSL https://get.rvm.io | bash -s stable && \
        source /home/runner/.rvm/scripts/rvm && \
        /home/runner/.rvm/bin/rvm install 3.1.1 --disable-binary
    - name: Install PackageCloud CLI
      run: /home/runner/.rvm/bin/rvm 3.1.1 do gem install package_cloud
    - name: Build sdist and x86_64
      uses: ./.github/actions/package_solarwinds_apm_x86_64
    - name: Upload sdist, x86_64 to PackageCloud
      env:
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      run: |
        /home/runner/.rvm/bin/rvm 3.1.1 do package_cloud push solarwinds/solarwinds-apm-python/python \
        dist/solarwinds_apm-$(grep __version__ ./solarwinds_apm/version.py | cut -d= -f 2 | tr -d ' "').tar.gz
        /home/runner/.rvm/bin/rvm 3.1.1 do package_cloud push solarwinds/solarwinds-apm-python/python \
        dist/solarwinds_apm-$(grep __version__ ./solarwinds_apm/version.py | cut -d= -f 2 | tr -d ' "')*.whl
    - name: Remove sdist, x86_64 builds and intermediates
      uses: ./.github/actions/clean_builds_intermediates

  launch_arm64:
    name: Launch arm64 ec2 runners
    needs:
      - build_publish_sdist_and_x86_64
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.launch.outputs.label }} # github runner label
      instance-id: ${{ steps.launch.outputs.instance-id }} # ec2 instance id
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.API_CI_GHA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.API_CI_GHA_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - id: launch
        uses: solarwindscloud/ec2-runner-action@main
        with:
          action: launch
          github-token: ${{ secrets.APM_CI_GHA_GITHUB_TOKEN }}
          runner-user: github
          runner-directory: /gh
          instance-type: t4g.medium
          ami-name: gha-arm64-ubuntu22-.*
          ami-owner: "858939916050"
          subnet-id: subnet-0fd499f8a50e41807
          security-group-ids: sg-0fd8d8cd6effda4a5

  build_publish_aarch64:
    name: Build and publish aarch64
    needs:
      - launch_arm64
    runs-on: ${{ needs.launch_arm64.outputs.label }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby 3.1.1
        run: |
          sudo apt-get update -y
          sudo apt-get install libssl-dev libreadline-dev libgdbm-dev openssl
          gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && \
          curl -sSL https://get.rvm.io | bash -s stable && \
          source /home/runner/.rvm/scripts/rvm && \
          /home/runner/.rvm/bin/rvm install 3.1.1 --disable-binary
      - name: Install PackageCloud CLI
        run: /home/runner/.rvm/bin/rvm 3.1.1 do gem install package_cloud
      - name: Build aarch64
        uses: ./.github/actions/package_solarwinds_apm_aarch64
      - name: Upload aarch64 to PackageCloud
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          /home/runner/.rvm/bin/rvm 3.1.1 do package_cloud push solarwinds/solarwinds-apm-python/python \
          dist/solarwinds_apm-$(grep __version__ ./solarwinds_apm/version.py | cut -d= -f 2 | tr -d ' "')*.whl
      - name: Remove sdist, aarch64 builds and intermediates
        uses: ./.github/actions/clean_builds_intermediates

  terminate_arm64:
    name: Terminate ec2 instances
    if: ${{ always() }}
    needs:
      - launch_arm64
      - build_publish_aarch64
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.API_CI_GHA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.API_CI_GHA_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: solarwindscloud/ec2-runner-action@main
        with:
          action: terminate
          github-token: ${{ secrets.APM_CI_GHA_GITHUB_TOKEN }}
          label: ${{ needs.launch_arm64.outputs.label }}
          instance-id: ${{ needs.launch_arm64.outputs.instance-id }}