# © 2023 SolarWinds Worldwide, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at:http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

name: Publish to TestPyPi

on:
  workflow_dispatch:

jobs:
  build_publish_sdist_and_x86_64:
    name: Build and publish sdist and x86_64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build x86_64
      uses: ./.github/actions/package_solarwinds_apm_x86_64
    - name: Install Twine
      run: pip install --upgrade --no-cache-dir --prefer-binary twine
    - name: Check distribution artifacts
      run: twine check dist/*
    - name: Publish to TestPyPi
      env:
        TWINE_NON_INTERACTIVE: 1
        TWINE_REPOSITORY: testpypi
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.SW_APM_TESTPYPI_UPLOAD_TOKEN }}
      run: twine upload dist/*

  build_publish_aarch64:
    name: Build and publish aarch64
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v3
    - name: Build aarch64 in container with QEMU
      run: |
        sudo docker run \
          --platform linux/arm64 \
          -e TWINE_NON_INTERACTIVE=1 \
          -e TWINE_REPOSITORY=testpypi \
          -e TWINE_USERNAME=__token__ \
          -e TWINE_PASSWORD=${{ secrets.SW_APM_TESTPYPI_UPLOAD_TOKEN }} \
          -v $(pwd):/home \
          -w /home \
          --rm quay.io/pypa/manylinux_2_28_aarch64:latest \
          /bin/bash -c "yum update -y; yum install -y python3-pip; \
          update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1; \
          pip install --upgrade pip; \
          pip install --upgrade twine; \
          make package; \
          twine check dist/*; \
          twine upload dist/*.whl"
