name: Publish to PyPi and Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version of release (e.g. 1.0.0)'
        required: true

env:
  RELEASE_NAME: rel-${{ github.event.inputs.version }}

jobs: 
  create_draft_release:
    name: Create draft release
    #needs: build_publish_and_release
    runs-on: ubuntu-latest
    steps:
    - name: Initialize git
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Create draft release
      run: gh release create ${{ env.RELEASE_NAME }} --repo appoptics/solarwinds-apm-python --title "${{ env.RELEASE_NAME }}" --target release/${{ env.RELEASE_NAME }} --draft
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
