name: Run tox tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    type: [opened, reopened]

jobs:
  run_tox_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-minor: ["7", "8", "9", "10"]
        apm-env: ["nh-staging", "ao-prod"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.${{ matrix.python-minor }}
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: '**/dev-requirements.txt'
    - name: Install tox
      run: pip install tox
    - name: Build extension
      run: make wrapper
    - name: Run tox
      run: tox -e py3${{ matrix.python-minor }}-${{ matrix.apm-env }}
