name: TEST Rhel8 Verify Installation

on:
  workflow_dispatch:
    inputs:
      install-registry:
        required: true
        description: 'Registry used for install tests, e.g. pypi, testpypi, packagecloud'
        type: choice
        default: 'pypi'
        options:
        - pypi
        - packagecloud
        - testpypi
      solarwinds-version:
        required: false
        description: 'Optional solarwinds-apm version, e.g. 0.0.3.2'

jobs:
  aarch64_py39_install_rhel8:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - uses: actions/checkout@v3
    - name: Run install test container with QEMU
      run: |
        sudo docker run \
        --platform linux/arm64 \
        -e PLATFORM=aarch64 \
        -e MODE=${{ github.event.inputs.install-registry }} \
        -e SOLARWINDS_APM_VERSION=${{ github.event.inputs.solarwinds-version }} \
        -e SW_APM_COLLECTOR_AO_PROD=${{ secrets.SW_APM_COLLECTOR_AO_PROD }} \
        -e SW_APM_COLLECTOR_PROD=${{ secrets.SW_APM_COLLECTOR_PROD }} \
        -e SW_APM_COLLECTOR_STAGING=${{ secrets.SW_APM_COLLECTOR_STAGING }} \
        -e SW_APM_SERVICE_KEY_AO_PROD=${{ secrets.SW_APM_SERVICE_KEY_AO_PROD }} \
        -e SW_APM_SERVICE_KEY_PROD=${{ secrets.SW_APM_SERVICE_KEY_PROD }} \
        -e SW_APM_SERVICE_KEY_STAGING=${{ secrets.SW_APM_SERVICE_KEY_STAGING }} \
        -h py3.9-rhel8 \
        -v $(pwd):/home \
        -w /home/tests/docker/install \
        --rm registry.fedoraproject.org/f33/python3 \
        /bin/sh -c "./_helper_run_install_tests.sh"