name: Verify TestPyPI Install

on:
  workflow_dispatch:

jobs:
  py36_install_centos8:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
    - name: Install pip and test deps (centos8 only)
      run: |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        dnf install -y python36-devel python3-pip gcc-c++
        dnf install -y unzip
        command -v python || ln -s /usr/bin/python3 /usr/local/bin/python
        command -v pip || ln -s /usr/bin/pip3 /usr/local/bin/pip
        pip install --upgrade pip >/dev/null
    - name: Install solarwinds-apm sdist (tar)
      run: pip install --extra-index-url https://test.pypi.org/simple/ solarwinds-apm --no-binary solarwinds-apm
    - name: Check sdist-installed agent startup
      run: |
        export SW_APM_DEBUG_LEVEL=6
        export SW_APM_SERVICE_KEY=invalid-token-for-testing-1234567890:servicename
        export TEST_EXP_LOG_MESSAGES=(
        ">> SSL Reporter using host='apm.collector.cloud.solarwinds.com' port='443' log='' clientid='inva...7890:servicename' buf=1000 maxTransactions='200' flushMaxWaitTime='5000' eventsFlushInterval='2' maxRequestSizeBytes='3000000' proxy=''"
        "Warning: There is an problem getting the API token authorized. Metrics and tracing for this agent are currently disabled. If you'd like to learn more about resolving this issue, please contact technicalsupport@solarwinds.com."
        )
        set +e
        result=$(opentelemetry-instrument python -c 'from solarwinds_apm import version; print(version.__version__)' 2>startup.log)
        logs_ok=true
        for expected in "${TEST_EXP_LOG_MESSAGES[@]}"; do
            grep -F "$expected" startup.log || logs_ok=false
        done
        if [ $logs_ok == false ]; then
            echo "FAILED! Expected messages were not found in startup.log"
            echo "-- startup.log content --"
            cat startup.log
            exit 1
        fi
        set -e
        echo -e "Agent startup verified successfully.\n"
    - name: Uninstall
      run: pip uninstall -y solarwinds-apm
    - name: Download solarwinds-apm bdist (wheel)
      run: pip install --extra-index-url https://test.pypi.org/simple/ solarwinds-apm
    - name: Check bdist-installed agent startup
      run: |
        export SW_APM_DEBUG_LEVEL=6
        export SW_APM_SERVICE_KEY=invalid-token-for-testing-1234567890:servicename
        export TEST_EXP_LOG_MESSAGES=(
        ">> SSL Reporter using host='apm.collector.cloud.solarwinds.com' port='443' log='' clientid='inva...7890:servicename' buf=1000 maxTransactions='200' flushMaxWaitTime='5000' eventsFlushInterval='2' maxRequestSizeBytes='3000000' proxy=''"
        "Warning: There is an problem getting the API token authorized. Metrics and tracing for this agent are currently disabled. If you'd like to learn more about resolving this issue, please contact technicalsupport@solarwinds.com."
        )
        set +e
        result=$(opentelemetry-instrument python -c 'from solarwinds_apm import version; print(version.__version__)' 2>startup.log)
        logs_ok=true
        for expected in "${TEST_EXP_LOG_MESSAGES[@]}"; do
            grep -F "$expected" startup.log || logs_ok=false
        done
        if [ $logs_ok == false ]; then
            echo "FAILED! Expected messages were not found in startup.log"
            echo "-- startup.log content --"
            cat startup.log
            exit 1
        fi
        set -e
        echo -e "Agent startup verified successfully.\n"

