name: Verify Installation

on:
  workflow_dispatch:
    inputs: 
      solarwinds-version:
        required: false
        description: 'solarwinds-apm version (e.g. solarwinds-apm@prerelease)'
        default: 'solarwinds-apm@latest'

env:
  SOLARWINDS_APM_VERSION: ${{ github.event.inputs.solarwinds-version }}

jobs:
  py36_install_centos8_testpypi:
    runs-on: ubuntu-latest
    container:
      image: centos:8
    steps:
    - name: Install and run test
      run: ./tests/docker/install/_helper_run_install_tests.sh
      shell: bash
      env:
        MODE: testpypi
  py37_install_debian10_packagecloud:
    runs-on: ubuntu-latest
    container:
      image: python:3.7-buster
    steps:
    - name: Install and run test
      run: ./tests/docker/install/_helper_run_install_tests.sh
      shell: bash
      env:
        MODE: packagecloud
  py38_install_alpine313_pypi:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-alpine3.13
    steps:
    - name: Install and run test
      run: ./tests/docker/install/_helper_run_install_tests.sh
      shell: bash
      env:
        MODE: pypi
